import { PrismaClient, AchievementCategory } from '@prisma/client'

const prisma = new PrismaClient()

export const achievements = [
  // GENERAL Achievements
  {
    key: 'welcome',
    category: AchievementCategory.GENERAL,
    nameEn: 'Welcome!',
    nameTr: 'Hoş Geldin!',
    descriptionEn: 'Complete your profile for the first time',
    descriptionTr: 'İlk kez profilini tamamla',
    icon: '👋',
    reputationBonus: 1,
    requiredCount: 1,
    isHidden: false,
    sortOrder: 1,
  },
  {
    key: 'veteran',
    category: AchievementCategory.GENERAL,
    nameEn: 'Veteran Player',
    nameTr: 'Deneyimli Oyuncu',
    descriptionEn: 'Be a member for 30 days',
    descriptionTr: '30 gün boyunca üye ol',
    icon: '🎖️',
    reputationBonus: 5,
    requiredCount: 1,
    isHidden: false,
    sortOrder: 10,
  },
  {
    key: 'legend',
    category: AchievementCategory.GENERAL,
    nameEn: 'Legend',
    nameTr: 'Efsane',
    descriptionEn: 'Be a member for 90 days',
    descriptionTr: '90 gün boyunca üye ol',
    icon: '👑',
    reputationBonus: 10,
    requiredCount: 1,
    isHidden: false,
    sortOrder: 11,
  },

  // MATCHMAKING Achievements
  {
    key: 'first_listing',
    category: AchievementCategory.MATCHMAKING,
    nameEn: 'First Listing',
    nameTr: 'İlk İlan',
    descriptionEn: 'Create your first listing',
    descriptionTr: 'İlk ilanını oluştur',
    icon: '📝',
    reputationBonus: 2,
    requiredCount: 1,
    isHidden: false,
    sortOrder: 20,
  },
  {
    key: 'active_poster',
    category: AchievementCategory.MATCHMAKING,
    nameEn: 'Active Poster',
    nameTr: 'Aktif İlan Veren',
    descriptionEn: 'Create 10 listings',
    descriptionTr: '10 ilan oluştur',
    icon: '📋',
    reputationBonus: 5,
    requiredCount: 10,
    isHidden: false,
    sortOrder: 21,
  },
  {
    key: 'listing_master',
    category: AchievementCategory.MATCHMAKING,
    nameEn: 'Listing Master',
    nameTr: 'İlan Ustası',
    descriptionEn: 'Create 50 listings',
    descriptionTr: '50 ilan oluştur',
    icon: '📚',
    reputationBonus: 15,
    requiredCount: 50,
    isHidden: false,
    sortOrder: 22,
  },
  {
    key: 'first_application',
    category: AchievementCategory.MATCHMAKING,
    nameEn: 'Ready to Play',
    nameTr: 'Oynamaya Hazır',
    descriptionEn: 'Apply to your first listing',
    descriptionTr: 'İlk ilanına başvur',
    icon: '🎮',
    reputationBonus: 2,
    requiredCount: 1,
    isHidden: false,
    sortOrder: 23,
  },
  {
    key: 'active_applicant',
    category: AchievementCategory.MATCHMAKING,
    nameEn: 'Active Applicant',
    nameTr: 'Aktif Başvuran',
    descriptionEn: 'Apply to 25 listings',
    descriptionTr: '25 ilana başvur',
    icon: '⚡',
    reputationBonus: 8,
    requiredCount: 25,
    isHidden: false,
    sortOrder: 24,
  },
  {
    key: 'match_maker',
    category: AchievementCategory.MATCHMAKING,
    nameEn: 'Match Maker',
    nameTr: 'Eşleştirici',
    descriptionEn: 'Accept 10 applications on your listings',
    descriptionTr: 'İlanlarına gelen 10 başvuruyu kabul et',
    icon: '🤝',
    reputationBonus: 10,
    requiredCount: 10,
    isHidden: false,
    sortOrder: 25,
  },

  // SOCIAL Achievements
  {
    key: 'first_message',
    category: AchievementCategory.SOCIAL,
    nameEn: 'Communicator',
    nameTr: 'İletişimci',
    descriptionEn: 'Send your first private message',
    descriptionTr: 'İlk özel mesajını gönder',
    icon: '💬',
    reputationBonus: 1,
    requiredCount: 1,
    isHidden: false,
    sortOrder: 30,
  },
  {
    key: 'social_butterfly',
    category: AchievementCategory.SOCIAL,
    nameEn: 'Social Butterfly',
    nameTr: 'Sosyal Kelebek',
    descriptionEn: 'Send 100 private messages',
    descriptionTr: '100 özel mesaj gönder',
    icon: '🦋',
    reputationBonus: 10,
    requiredCount: 100,
    isHidden: false,
    sortOrder: 31,
  },
  {
    key: 'team_player',
    category: AchievementCategory.SOCIAL,
    nameEn: 'Team Player',
    nameTr: 'Takım Oyuncusu',
    descriptionEn: 'Receive 10 positive ratings',
    descriptionTr: '10 pozitif değerlendirme al',
    icon: '⭐',
    reputationBonus: 8,
    requiredCount: 10,
    isHidden: false,
    sortOrder: 32,
  },
  {
    key: 'all_star',
    category: AchievementCategory.SOCIAL,
    nameEn: 'All-Star',
    nameTr: 'Yıldız Oyuncu',
    descriptionEn: 'Receive 50 positive ratings',
    descriptionTr: '50 pozitif değerlendirme al',
    icon: '🌟',
    reputationBonus: 20,
    requiredCount: 50,
    isHidden: false,
    sortOrder: 33,
  },

  // SKILL Achievements
  {
    key: 'aim_beginner',
    category: AchievementCategory.SKILL,
    nameEn: 'Aim Beginner',
    nameTr: 'Nişancı Çaylak',
    descriptionEn: 'Complete 10 aim trainer sessions',
    descriptionTr: '10 aim trainer oturumu tamamla',
    icon: '🎯',
    reputationBonus: 3,
    requiredCount: 10,
    isHidden: false,
    sortOrder: 40,
  },
  {
    key: 'aim_enthusiast',
    category: AchievementCategory.SKILL,
    nameEn: 'Aim Enthusiast',
    nameTr: 'Nişan Tutkunu',
    descriptionEn: 'Complete 50 aim trainer sessions',
    descriptionTr: '50 aim trainer oturumu tamamla',
    icon: '🏹',
    reputationBonus: 8,
    requiredCount: 50,
    isHidden: false,
    sortOrder: 41,
  },
  {
    key: 'aim_master',
    category: AchievementCategory.SKILL,
    nameEn: 'Aim Master',
    nameTr: 'Nişan Ustası',
    descriptionEn: 'Complete 200 aim trainer sessions',
    descriptionTr: '200 aim trainer oturumu tamamla',
    icon: '🎪',
    reputationBonus: 20,
    requiredCount: 200,
    isHidden: false,
    sortOrder: 42,
  },
  {
    key: 'sharpshooter',
    category: AchievementCategory.SKILL,
    nameEn: 'Sharpshooter',
    nameTr: 'Keskin Nişancı',
    descriptionEn: 'Achieve 90% accuracy or higher in aim trainer',
    descriptionTr: 'Aim trainer\'da %90 veya üzeri isabet oranı yakala',
    icon: '🎰',
    reputationBonus: 15,
    requiredCount: 1,
    isHidden: false,
    sortOrder: 43,
  },
  {
    key: 'high_scorer',
    category: AchievementCategory.SKILL,
    nameEn: 'High Scorer',
    nameTr: 'Yüksek Skor',
    descriptionEn: 'Score 300 or higher in aim trainer',
    descriptionTr: 'Aim trainer\'da 300 veya üzeri puan al',
    icon: '🔥',
    reputationBonus: 10,
    requiredCount: 1,
    isHidden: false,
    sortOrder: 44,
  },

  // REPUTATION Achievements
  {
    key: 'trustworthy',
    category: AchievementCategory.REPUTATION,
    nameEn: 'Trustworthy',
    nameTr: 'Güvenilir',
    descriptionEn: 'Reach 25 reputation points',
    descriptionTr: '25 itibar puanına ulaş',
    icon: '🛡️',
    reputationBonus: 5,
    requiredCount: 1,
    isHidden: false,
    sortOrder: 50,
  },
  {
    key: 'respected',
    category: AchievementCategory.REPUTATION,
    nameEn: 'Respected',
    nameTr: 'Saygın',
    descriptionEn: 'Reach 50 reputation points',
    descriptionTr: '50 itibar puanına ulaş',
    icon: '💎',
    reputationBonus: 10,
    requiredCount: 1,
    isHidden: false,
    sortOrder: 51,
  },
  {
    key: 'elite',
    category: AchievementCategory.REPUTATION,
    nameEn: 'Elite Member',
    nameTr: 'Elit Üye',
    descriptionEn: 'Reach 100 reputation points',
    descriptionTr: '100 itibar puanına ulaş',
    icon: '💫',
    reputationBonus: 25,
    requiredCount: 1,
    isHidden: false,
    sortOrder: 52,
  },
]

async function seedAchievements() {
  console.log('🌱 Seeding achievements...')

  for (const achievement of achievements) {
    await prisma.achievement.upsert({
      where: { key: achievement.key },
      update: achievement,
      create: achievement,
    })
  }

  console.log('✅ Achievements seeded successfully!')
}

// Run if called directly
if (require.main === module) {
  seedAchievements()
    .catch((e) => {
      console.error('❌ Error seeding achievements:', e)
      process.exit(1)
    })
    .finally(async () => {
      await prisma.$disconnect()
    })
}

export default seedAchievements
